services:
  # sa-todo-api:
  #   build: ./sa-todo-api
  #   container_name: sa-todo-api
  #   hostname: 'sa-todo-api'
  #   networks:
  #   - sa-todo.net
  #   volumes:
  #   - ./sa-todo-api/src:/sa-todo-api/src
  #   ports:
  #   - 3000:3000
  #   links:
  #   - mongodb
  # db:
  #   image: mongo:4.2.1
  #   container_name: sa-todo-db
  #   hostname: 'sa-todo-db'
  #   volumes:
  #   - .data/db:/data/db
  #   networks:
  #   - sa-todo.net
  #   ports:
  #   - 27017:27017
   sa-todo-web:
    build:
      args:
        - NODE_VERSION
        - ANGULAR_CLI_VERSION
      context: ./super-awesome-to-do-list-5000
      dockerfile: .docker/${UI_DOCKERFILE}.Dockerfile
    container_name: sa-todo-web
    hostname: 'sa-todo-web'
    networks:
    - sa-todo.net
    volumes:
    # empty volume mapping for debugging purposes
    # - /usr/share/nginx/html/node_modules
    # - ./super-awesome-to-do-list-5000/:/build/dist
    # - ./super-awesome-to-do-list-5000/dist:/usr/share/nginx/html
    - ./super-awesome-to-do-list-5000/src:/app/src
    ports:
    - 80:80
networks:
  sa-todo.net:
    driver: bridge
