services:
  sa-todo-web:
    build:
      args:
        - NODE_BUILDER_VERSION
        - ANGULAR_CLI_VERSION
      context: ./super-awesome-to-do-list-5000
      dockerfile: .docker/${UI_DOCKERFILE}.Dockerfile
    container_name: sa-todo-web
    networks:
    - sa-todo.net
    volumes:
    # empty volume mapping for debugging purposes
    # - /usr/share/nginx/html/node_modules
    # - ./super-awesome-to-do-list-5000/:/build/dist
    # - ./super-awesome-to-do-list-5000/dist:/usr/share/nginx/html
    - ./super-awesome-to-do-list-5000/src:/app/src
    ports:
    - 80:80
  sa-todo-api:
    build:
      args:
        - NODE_VERSION
      context: ./super-awesome-to-do-list-api
      dockerfile: .docker/Dockerfile
    container_name: sa-todo-api
    networks:
    - sa-todo.net
    volumes:
    - ./super-awesome-to-do-list-api/src:/app/src
    ports:
    - 3000:3000
    links:
    - sa-todo-db
  sa-todo-db:
    build:
      context: ./super-awesome-to-do-list-db
      dockerfile: .docker/Dockerfile
    container_name: sa-todo-db
    volumes:
    - ./super-awesome-to-do-list-db/.data/db:/data/db
    networks:
    - sa-todo.net
    ports:
    - 27017:27017
networks:
  sa-todo.net:
    driver: bridge
